// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

// Test for Happy day scenario


// Paste the contents from proof.json generated from zokrates steps

    
// Test for Rainy day scenario
